FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS runtime-stage

WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY KAMAR/*.csproj ./KAMAR/
COPY KamarCalendar/*.csproj ./KamarCalendar/
RUN dotnet restore

WORKDIR /app/KamarCalendar
CMD ASPNETCORE_URLS=http://+:$PORT dotnet watch run --urls http://0.0.0.0:$PORT
