version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=5000
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    volumes:
      - ./KAMAR:/app/KAMAR
      - ./KamarCalendar:/app/KamarCalendar
